# Generated by Django 2.2.17 on 2021-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200517_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alternate_title',
            field=models.CharField(help_text='An alternative title to use on pages with this category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
